version: "3"

services:

  koala-lms-devel:
    build:
      context: ../..
      dockerfile: ./docker/devel/Dockerfile
    image: "registry.gitlab.com/koala-lms/lms:devel"
    container_name: koala-lms-devel
    hostname: koala-lms-devel
    environment:
      DEBUG: 1
    ports:
      - 8080:8080
