version: "3"

services:

  koala-lms:
    image: "registry.gitlab.com/koala-lms/lms:devel"
    container_name: koala-lms
    hostname: koala-lms
    restart: always
    links:
      - db
    environment:
      FIXTURE: "./fixtures/sample-fr.json"
    ports:
      - 8080:8080
    volumes:
      - ./settings.py:/koala_lms/lms/local_settings.py

  db:
    image: mariadb:latest
    container_name: db
    hostname: db
    restart: always
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800]
    environment:
      MYSQL_ROOT_PASSWORD: koala
      MYSQL_DATABASE: koala
      MYSQL_USER: koala
      MYSQL_PASSWORD: koala
