version: "3"

services:

  demo.koala-lms.org:
    build:
      context: ../../
      dockerfile: ./docker/demo.koala-lms.org/Dockerfile
    image: "registry.gitlab.com/koala-lms/lms/demo:latest"
    container_name: demo.koala-lms.org
    hostname: demo.koala-lms.org
    environment:
      TIME_ZONE: 'Europe/Paris'
      FIXTURE: "./fixtures/sample-fr.json"
      DEMO: 1
    ports:
      - 8080:8080
