# Generated by Django 2.1.7 on 2019-03-20 12:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import learning.permissions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='You can use the <a href="https://www.markdownguide.org/basic-syntax/" target="_blank">Markdown</a> syntax here.', verbose_name='Description')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Published the')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last updated the')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['name'],
            },
            bases=(learning.permissions.ObjectPermissionManagerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='Rank')),
                ('minimal_allowed_score', models.PositiveIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Minimal allowed score')),
                ('success_score', models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Success score')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_activities', to='learning.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'course activity',
                'verbose_name_plural': 'course activities',
                'ordering': ['rank'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='You can use the <a href="https://www.markdownguide.org/basic-syntax/" target="_blank">Markdown</a> syntax here.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_activities', to='learning.Course', verbose_name='Course'),
        ),
        migrations.AlterUniqueTogether(
            name='courseactivity',
            unique_together={('rank', 'course')},
        ),
    ]
