version: "3"

services:

  demo.koala-lms.org:
    image: "registry.gitlab.com/koala-lms/lms:devel"
    container_name: demo.koala-lms.org
    hostname: demo.koala-lms.org
    environment:
      TIME_ZONE: 'Europe/Paris'
      FIXTURE: "./fixtures/sample-fr.json"
      DEMO: 1
      DEMONSTRATION_LOGIN: "erik-orsenna"
    ports:
      - 8080:8080
